# Generated by Django 5.2.6 on 2025-09-25 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('calorias', models.FloatField()),
                ('proteinas', models.FloatField()),
                ('carbohidratos', models.FloatField()),
                ('grasas', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistroComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alimento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
